### ISSUE TITLE
Instruction wrongly executed after core branch

### ISSUE THREAD

**Issue by timdudu** [pulp-platform/riscv#58] opened 2018-12-19 01:27 UTC
Hi,
Here is the assembly code that can reproduce the issue.
     5a2:	30472703          	lw	a4,772(a4)   // load data from address 0x4002_c304
     5a6:	f81630e3          	p.bneimm	a2,1,526  //a2==1, should jump to 526
     5aa:	8321                	srli	a4,a4,0x8  //

Core load data from address 0x4002_c304 when pc=5a2. The data is not got immediately and be delayed several cycles. When core jump to 0x526 by executing jump instruction in 5a6, instruction in 5aa should not be executed. But actually it's executed.  This issue happens when instruction in 5aa uses the 
 same register(a4) in 5a2.  id_ready is deasserted because of load_stall and instr_valid is not cleared. 

![issue snap](https://user-images.githubusercontent.com/29726453/50192669-33b07900-036e-11e9-9985-630f84b75a1a.PNG)

Thanks,
Tim

**Comment by davideschiavone** [comment] 2018-12-19 15:45
Thanks a lot for reporting it,

Are you using the MASTER branch? which commit are you using?

I will try to reproduce it and fix it!

Best
Davide

**Comment by hyf6661669** [comment] 2018-12-19 15:57
@timdudu

Hi, I think the problem comes from "riscv_controller.sv":
```
if (
          ( (data_req_ex_i == 1'b1) && (regfile_we_ex_i == 1'b1) |
           (wb_ready_i == 1'b0) && (regfile_we_wb_i == 1'b1)
          ) &
          ( (reg_d_ex_is_reg_a_i == 1'b1) | (reg_d_ex_is_reg_b_i == 1'b1) | (reg_d_ex_is_reg_c_i == 1'b1) | (regfile_waddr_ex_i == regfile_alu_waddr_id_i))
       )
    begin
      deassert_we_o   = 1'b1;
      load_stall_o    = 1'b1;
    end
```
When the instruction "srli	a4,a4,0x8" is in ID, it is actually invalid because the CPU can find that the branch instruction "p.bneimm	a2,1,526" in EX needs to be taken. Maybe we could add another signal ```branch_taken_ex_i``` to fix this:
```
if (
          ( (data_req_ex_i == 1'b1) && (regfile_we_ex_i == 1'b1) |
           (wb_ready_i == 1'b0) && (regfile_we_wb_i == 1'b1)
          ) &
          ( (reg_d_ex_is_reg_a_i == 1'b1) | (reg_d_ex_is_reg_b_i == 1'b1) | (reg_d_ex_is_reg_c_i == 1'b1) | (regfile_waddr_ex_i == regfile_alu_waddr_id_i)) & (~branch_taken_ex_i)
       )
    begin
      deassert_we_o   = 1'b1;
      load_stall_o    = 1'b1;
    end
```

**Comment by hyf6661669** [comment] 2018-12-19 16:16
What's more, if the instruction in 0x5aa wants to write data into the same register a4, such as "add a4, x0, x8", it will also lead to "load_stall_o = 1" because "regfile_waddr_ex_i == regfile_alu_waddr_id_i"

**Comment by timdudu** [comment] 2018-12-20 01:00
@davideschiavone I'm using pulpinov1 branch. please try latest commit. Thanks.

**Comment by timdudu** [comment] 2018-12-20 01:03
@hyf6661669 Yes, I have the same understanding on this issue.

**Comment by timdudu** [comment] 2018-12-20 01:04
@hyf6661669 Yes, I have the same understanding on this issue. Thanks.

**Comment by hyf6661669** [comment] 2018-12-20 01:14
@timdudu  I'm using master branch and the problem is the same as yours.

**Comment by davideschiavone** [comment] 2018-12-20 15:57
Sorry, 

I cannot reproduce your issue. Here is what I have done:

I executed this piece of code on PULPissimo using the MASTER branch

1c008b54:	411c                	lw	a5,0(a0)
1c008b56:	00173363          	p.bneimm	a4,1,1c008b5c
1c008b5a:	83a1                	srli	a5,a5,0x8
1c008b5c:	0001                	nop

which is similar to yours.

a4 contains 2 so branch if not equal is actually jumping to the nop at 1C008B5C.

As you told me that the problem happens when load takes several cycles, I forced the valid to arrive 8 cycles after the grant. The grant arrives at the same cycle of the request.

Here is my trace:

267473 1c008b54 00052783 lw               x15, 0(x10)         x15=1c008080 x10:1a104004  PA:1a104004
267474 1c008b56 00173363 p.bneimm   x14, 1, 6             x14:00000002
267485 1c008b5c 00000013 nop                                 

If you do a git diff between the master and pulpino you may find the reason of this bug as we had already in the past a similar problem that may have not been backported to pulpino.

@hyf6661669 when did you try it with the master branch? 

Thanks a lot
Davide

**Comment by hyf6661669** [comment] 2018-12-20 16:07
@davideschiavone  I'm using the latest master branch. But at present my ModelSim is broken so I can't do simulations.

Can you show the wave under this situation?

**Comment by hyf6661669** [comment] 2019-01-09 08:34
@davideschiavone  
@timdudu 
I think this problem is just a misunderstanding. In fact, ri5cy is not allowed to excute later instructions if a load/store instruction doesn't get asserted ```data_rvalid_i```, even if the ```rs1, rs2, rd``` of the load instruction has nothing to do with that of later instructions.

**Comment by davideschiavone** [comment] 2019-01-09 15:04
Ok so shall you guys close the issue?

**Comment by timdudu** [comment] 2019-01-16 06:00
@hyf6661669
I don't think this is a misunderstanding. You said "ri5cy is not allowed to excute later instructions if a load/store instruction doesn't get asserted data_rvalid_i, even if the rs1, rs2, rd of the load instruction has nothing to do with that of later instructions." But actually, in my test, 5a6 is executed before getting data_rvalid_i and 5a8 is executed when get data_rvalid_i.

**Comment by timdudu** [comment] 2019-01-16 07:57
@davideschiavone
"In the yellow cursor, the instruction in the ID stage is indeed the SRLI and both load_stall_o and deassert_we_o of the controller go to '1'." In my test, load_stall_o and deassert_we_o are also go to 1, but when get data_rvalid_i, this two signals go to 0 and the result of SRLI is written to register.
![capture](https://user-images.githubusercontent.com/29726453/51234309-5c488480-19a7-11e9-9e01-112babe176a4.PNG)

**Comment by hyf6661669** [comment] 2019-01-17 12:15
@timdudu 
Sorry for my wrong words...  The instruciton following Load/Store is able to enter EX if Load/Store gets asserted ```data_gnt_i```.

Actually in riscv_ex_stage.sv, you can see:
```
assign ex_ready_o = (~apu_stall & alu_ready & mult_ready & lsu_ready_ex_i & wb_ready_i & ~wb_contention) | (branch_in_ex_i);
```
And ```riscv_ex_stage.lsu_ready_ex_i = 1``` means that ```riscv_load_store_unit.data_gnt_i = 1```. But at present, ```riscv_load_store_unit.CS = IDLE```, so ```riscv_load_store_unit.lsu_ready_wb_o = riscv_ex_stage.wb_ready_i = 1```, and ```riscv_ex_stage.ex_ready_o = 1```. In your example,  it allows the instruction ```p.bneimm	a2,1,526``` to enter EX.

**Comment by timdudu** [comment] 2019-01-18 07:31
@hyf6661669
So do you agree it is an issue?

**Comment by hyf6661669** [comment] 2019-01-18 07:50
@timdudu 
Yes, from your figure it seems that the instruction ```srli	a4,a4,0x8``` writes 0x0000_0101 into register x14, which is not expected.

**Comment by davideschiavone** [comment] 2019-01-21 08:37
> @davideschiavone
> "In the yellow cursor, the instruction in the ID stage is indeed the SRLI and both load_stall_o and deassert_we_o of the controller go to '1'." In my test, load_stall_o and deassert_we_o are also go to 1, but when get data_rvalid_i, this two signals go to 0 and the result of SRLI is written to register.
> ![capture](https://user-images.githubusercontent.com/29726453/51234309-5c488480-19a7-11e9-9e01-112babe176a4.PNG)

This looks pretty much the same I tried to reproduce but it works for me. Can I see what happens to the branch? You can have a look at my waveforms.

Also, can you please try the master branch? fixes and development have been implemented in the master, so maybe I can't see the bug because it has been fixed in the master branch.

Best
Davide

**Comment by bluewww** [comment] 2019-03-09 23:05
I'm closing this as you have reported it to be fixed.

**Closed by bluewww** 2019-03-09 23:05 UTC
